### ISSUE TITLE
Unable to Deploy to AWS Bean Stalk from Bamboo

### ISSUE THREAD

**Issue by manojreddygmr** [Kentico/kontent-sample-app-net#111]
### Brief bug description
I am trying to deploy to Beanstalk from bamboo but failing with errors below whereas if I deploy from VS 2017 to the same env deployment is getting succeeded.

 Command hooks (HooksExecutor.exe appdeploy\enact) failed
2020-05-20 05:59:50,865 [ERROR] Error encountered during build of Hook-EnactAppDeploy: Command hooks failed
Traceback (most recent call last):
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command hooks failed
2020-05-20 05:59:50,865 [ERROR] -----------------------BUILD FAILED!------------------------
2020-05-20 05:59:50,865 [ERROR] Unhandled exception during build: Command hooks failed
Traceback (most recent call last):
  File "cfn-init", line 171, in <module>
  File "cfnbootstrap\construction.pyc", line 129, in build
  File "cfnbootstrap\construction.pyc", line 530, in build
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command hooks failed
What went wrong?
Beanstalk Env creation 
### Expected behavior
Site to be up
What the correct behavior is?
 Command hooks (HooksExecutor.exe appdeploy\enact) failed
2020-05-20 05:59:50,865 [ERROR] Error encountered during build of Hook-EnactAppDeploy: Command hooks failed
Traceback (most recent call last):
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command hooks failed
2020-05-20 05:59:50,865 [ERROR] -----------------------BUILD FAILED!------------------------
2020-05-20 05:59:50,865 [ERROR] Unhandled exception during build: Command hooks failed
Traceback (most recent call last):
  File "cfn-init", line 171, in <module>
  File "cfnbootstrap\construction.pyc", line 129, in build
  File "cfnbootstrap\construction.pyc", line 530, in build
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command hooks failed
### Test environment

 - Platform/OS: [e.g. .NET Core 2.1, iOS] IIS 10.0 running on 64bit Windows Server 2016/2.5.5
 - Browser [e.g. chrome, safari] Mozilla Firefox
[siteerror.docx](https://github.com/Kentico/kontent-sample-app-net/files/4655005/siteerror.docx)

### Screenshots

Add links to screenshots, if possible.

**Comment by petrsvihlik** [comment]
Hi @manojreddygmr ,
this seems like a problem with the deployment configuration rather than with the sample site itself. This sample site is a standard ASP.NET Core MVC project that follows all the Microsoft's conventions and best practices. We regularly test deployments to Azure Web Apps and they work fine.

Please try to consult the problem with Amazon AWS support first. If you run into any runtime errors related to this project, please feel free to reopen this issue and share the stack trace. We'll be able to help you then.

Thanks!
